 // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI3vD3fmIa0Wq1oVCW9liqI5mi3WFRMAM',
    appId: '1:345513654512:web:e7f72586cc0f35c32f2a35',
    messagingSenderId: '345513654512',
    projectId: 'hadirin-2d821',
    authDomain: 'hadirin-2d821.firebaseapp.com',
    storageBucket: 'hadirin-2d821.firebasestorage.app',
    measurementId: 'G-4YVM2RWMF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEcT07PgMF0grZGxNodE8SvUP-rXovyGE',
    appId: '1:345513654512:android:6df2a800cbd31b7f2f2a35',
    messagingSenderId: '345513654512',
    projectId: 'hadirin-2d821',
    storageBucket: 'hadirin-2d821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTBSBgkT0GPUCEq-mywiAHcSlL443DvGw',
    appId: '1:345513654512:ios:866f03b5deb47bf42f2a35',
    messagingSenderId: '345513654512',
    projectId: 'hadirin-2d821',
    storageBucket: 'hadirin-2d821.firebasestorage.app',
    iosBundleId: 'com.example.hadirin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTBSBgkT0GPUCEq-mywiAHcSlL443DvGw',
    appId: '1:345513654512:ios:866f03b5deb47bf42f2a35',
    messagingSenderId: '345513654512',
    projectId: 'hadirin-2d821',
    storageBucket: 'hadirin-2d821.firebasestorage.app',
    iosBundleId: 'com.example.hadirin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI3vD3fmIa0Wq1oVCW9liqI5mi3WFRMAM',
    appId: '1:345513654512:web:d7636cb8ec0e53712f2a35',
    messagingSenderId: '345513654512',
    projectId: 'hadirin-2d821',
    authDomain: 'hadirin-2d821.firebaseapp.com',
    storageBucket: 'hadirin-2d821.firebasestorage.app',
    measurementId: 'G-KCNW2DDE4C',
  );
}
